---
namespace: 2chevskii
name: windows
description: Custom modules for Windows automation
version: 1.0.0
authors:
  - 2CHEVSKII <prsroman3@gmail.com>
readme: README.md
license_file: LICENSE
tags: [windows, powershell, winget, packaging, package_management]

build_ignore:
  - .venv
  - .vscode
  - bin
  - dist
  - .editorconfig
  - .gitignore
  - requirements.txt

repository: https://github.com/2chevskii/dvchevskii.windows.git
documentation: http://github.com/2chevskii/dvchevskii.windows
homepage: http://github.com/2chevskii/dvchevskii.windows
issues: https://github.com/2chevskii/dvchevskii.windows/issues
