namespace: dvchevskii
name: windows
version: 1.0.0
readme: README.md
authors:
  - 2CHEVSKII <prsroman3@gmail.com>
description: Custom modules for Windows automation
license:
  - MIT
tags: [windows, powershell, winget]
repository: https://github.com/2chevskii/dvchevskii.windows.git
documentation: http://docs.example.com
homepage: http://github.com/2chevskii/dvchevskii.windows
issues: https://github.com/2chevskii/dvchevskii.windows/issues

build_ignore:
  - .venv
  - .vscode
  - bin
  - dist
  - .editorconfig
  - .gitignore
  - requirements.txt
