on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install -r requirements.txt
      - run: ansible-galaxy collection build --output-path dist .
      - uses: actions/upload-artifact@v4
        with:
          name: 2chevskii.windows
          path: dist/
