on:
  release:
    types: published
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install -r requirements.txt
      - id: extract_version
        run: echo "version=$(echo '${{ github.event.release.tag_name }}' | cut -d 'v' -f 2-)" >> $GITHUB_OUTPUT
      - uses: robinraju/release-downloader@v1
        with:
          repository: 2chevskii/dvchevskii.windows
          tag: ${{ github.event.release.tag_name }}
          fileName: "dvchevskii-windows-${{ steps.extract_version.outputs.version }}.tar.gz"
          out-file-path: dist/
      - run: ansible-galaxy collection publish --api-key '${{ secrets.API_KEY }}' 'dist/dvchevskii-windows-${{ steps.extract_version.outputs.version }}.tar.gz'
    environment:
      name: ansible-galaxy
      url: https://galaxy.ansible.com/ui/repo/published/dvchevskii/windows/?version=${{ steps.extract_version.outputs.version }}
