on:
  release:
    types: published
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install -r requirements.txt
      # - uses: robinraju/release-downloader@v1
      #   with:
      #     repository: 2chevskii/dvchevskii.windows
      #     tag: ${{ github.ref_name }}
      # - run: ansible-galaxy collection publish --api-key
